flexbox/weshipit.today

- libs/weshipit-ui/src/lib/hero/hero.tsx
- update description
- update description
> description

- .storybook/main.js
- .storybook/tsconfig.json
- libs/weshipit-ui/.storybook/main.js
- libs/weshipit-ui/.storybook/preview.js
- libs/weshipit-ui/.storybook/styles.css
- libs/weshipit-ui/.storybook/tailwind-imports.css
- libs/weshipit-ui/.storybook/tsconfig.json
- libs/weshipit-ui/postcss.config.js
- libs/weshipit-ui/project.json
- libs/weshipit-ui/src/lib/header/header.stories.tsx
- libs/weshipit-ui/src/lib/hero/hero.stories.tsx
- libs/weshipit-ui/tailwind.config.js
- libs/weshipit-ui/tsconfig.json
- libs/weshipit-ui/tsconfig.lib.json
- nx.json
- package.json
- yarn.lock
- add storybook
- add tailwind for storybook
> add storybok with tailwind

- README.md
- changelog.config.js
- docs/nx.md
- package.json
- yarn.lock
BREAKING CHANGE: 🧨 use git-cz all the time please
> feat: 🎸 better dx with git-cz

- apps/weshipit/components/layout.tsx
- apps/weshipit/pages/index.tsx
- libs/ui/src/lib/clients-list/clients-list-homepage.tsx
- feat: 🎸 Link for clients on index
- feat: 🎸 grayscale for clients on homepage
> Clients CSS 

- apps/weshipit/components/layout.tsx
- apps/weshipit/pages/react-native-api.tsx
- libs/ui/src/lib/header/header.tsx
- feat: 🎸 init react-native-api
- feat: 🎸 Add withButton? on header
> React-native-api page

- apps/weshipit/pages/api/og.tsx
> fix: 🐛 ogImage

- apps/weshipit/pages/404.tsx
> feat: 🎸 404 page

- apps/weshipit/pages/api/og.tsx
- apps/weshipit/tailwind.config.js
> Tailwind for og:image

- libs/ui/src/lib/footer/footer.tsx
> feat: 🎸 change job page location on Notion new intern found

- apps/weshipit/pages/qr.tsx
- apps/weshipit/tailwind.config.js
- libs/ui/src/lib/hero/hero.tsx
- libs/ui/tailwind.config.js
- package.json
- yarn.lock
> feat: 🎸 add landing page for people who QR code business card

- apps/weshipit/components/layout.tsx
- apps/weshipit/pages/index.tsx
- apps/weshipit/pages/react-native-tools/[slug].tsx
- apps/weshipit/pages/react-native-tools/index.tsx
- libs/ui/src/index.ts
- libs/ui/src/lib/api-list/api-card.tsx
- libs/ui/src/lib/button/button.tsx
- libs/ui/src/lib/card-gradient/card-gradient.spec.tsx
- libs/ui/src/lib/card-gradient/card-gradient.tsx
- libs/ui/src/lib/card-homepage/card-homepage.tsx
- libs/ui/src/lib/card/card.tsx
- libs/ui/src/lib/footer/footer.tsx
- libs/ui/src/lib/header/header.tsx
- libs/ui/src/lib/text/text.tsx
> feat: 🎸 Add Darkmode and cva gradient cards

- apps/weshipit/pages/api/links.ts
- apps/weshipit/pages/clients.tsx
- apps/weshipit/pages/index.tsx
- apps/weshipit/pages/onboarding.tsx
- apps/weshipit/pages/qr.tsx
- apps/weshipit/pages/react-native-tools/[slug].tsx
> feat: 🎸 Add button for compagny logo

- apps/weshipit/pages/api/og.tsx
- libs/ui/tailwind.config.js
> fix: 🐛 Add tailwind custom font for og:img

- .github/PULL_REQUEST_TEMPLATE.md
- apps/figmatostore/jest.config.ts
- apps/githubtolinkedin/jest.config.ts
- apps/weshipit/jest.config.ts
- apps/weshipit/next.config.js
- apps/weshipit/pages/react-native-tools/[slug].tsx
- apps/weshipit/pages/react-native-tools/index.tsx
- libs/ui/jest.config.ts
- libs/ui/src/index.ts
- libs/ui/src/lib/api-list/api-card-logo.spec.tsx
- libs/ui/src/lib/api-list/api-card-logo.tsx
- libs/ui/src/lib/api-list/api-card.tsx
- libs/ui/src/lib/api-list/api-list.d.ts
- libs/ui/src/lib/api-list/api-list.fixture.ts
- libs/ui/src/lib/api-list/api-list.tsx
- libs/ui/src/lib/react-native-tools/type-filter/type-filter.spec.tsx
- libs/ui/src/lib/react-native-tools/type-filter/type-filter.tsx
- package.json
- yarn.lock
> feat: 🎸 add filter for api type with the data from airtable

- apps/weshipit/pages/clients.tsx
- apps/weshipit/pages/index.tsx
- libs/ui/src/lib/clients-list/clients-list-homepage.tsx
> fix: 🐛 rename clients to customers

- apps/weshipit/pages/clients.tsx
- apps/weshipit/pages/consulting.tsx
- apps/weshipit/pages/index.tsx
- apps/weshipit/pages/react-native-tools/[slug].tsx
- apps/weshipit/pages/react-native-tools/index.tsx
- libs/ui/src/lib/button/button.stories.tsx
- libs/ui/src/lib/button/button.tsx
- libs/ui/src/lib/card-gradient/card-gradient.tsx
- libs/ui/src/lib/card-homepage/card-homepage.tsx
> refactor: 💡 rename all intent to variant for CVA with tailwind

- apps/weshipit/pages/react-native-tools/[slug].tsx
- libs/ui/src/index.ts
- libs/ui/src/lib/card-homepage/card-homepage.tsx
- libs/ui/src/lib/card/card-bootcamp.spec.tsx
- libs/ui/src/lib/card/card-bootcamp.tsx
- libs/ui/src/lib/card/card-checklist.spec.tsx
- libs/ui/src/lib/card/card-checklist.tsx
- libs/ui/src/lib/card/card-consultation.spec.tsx
- libs/ui/src/lib/card/card-consultation.tsx
- libs/ui/src/lib/tool-list/tool-website-preview.tsx
- libs/ui/src/lib/useful-resources/useful-resources.spec.tsx
- libs/ui/src/lib/useful-resources/useful-resources.tsx
> More useful resources

- apps/weshipit/pages/consulting.tsx
> feat: 🎸 Add video background for consulting

- apps/weshipit/pages/audit/index.tsx
- apps/weshipit/pages/react-native-tools/index.tsx
- libs/ui/src/index.ts
- libs/ui/src/lib/footer/footer.tsx
- libs/ui/src/lib/react-native-tools/type-filter/type-filter.tsx
- libs/ui/src/lib/tool-list/get-variant-from-type.ts
- libs/ui/src/lib/tool-list/tool-card.tsx
- libs/ui/src/lib/tool-list/tool-type-badge.tsx
> feat: 🎸 add /audit page

- libs/ui/src/lib/text/text.tsx
> fix: 🐛 migrate to isomorphic text

- libs/ui/src/lib/tool-list/call-to-action-cards.tsx
> fix: 🐛 cta card css

- apps/weshipit/pages/react-native-starters/index.tsx
> feat: 🎸 add badge to display stack and scope for starters

- apps/weshipit/pages/react-native-tools/index.tsx
> fix: 🐛 filter for tools

- apps/weshipit/pages/react-native-tools/[slug].tsx
- libs/ui/src/index.ts
- libs/ui/src/lib/not-found/not-found.tsx
> fix: 🐛 handle ApolloError on nextjs getServerSideProps

- apps/weshipit/pages/french-react-native-apps.tsx
> feat: 🎸 add cta in French react apps

- apps/weshipit/pages/french-react-native-apps.tsx
- libs/ui/src/lib/app-badge/AppBadge.tsx
- libs/ui/src/lib/header/header-links-onboarding.tsx
> fix: 🐛 header button

- apps/weshipit/pages/api/links.ts
- apps/weshipit/pages/french-react-native-apps.tsx
> fix: 🐛 Add call to action to add French React Native apps

- README.md
- apps/weshipit/next-env.d.ts
- apps/weshipit/pages/api/faq.ts
- apps/weshipit/pages/french-react-native-apps.tsx
- apps/weshipit/pages/pricing.tsx
- libs/ui/src/lib/app-badge/AppBadge.tsx
- yarn.lock
> feat: 🎸 add faq section for pricing page

- apps/weshipit/next-env.d.ts
- apps/weshipit/pages/consulting.tsx
- apps/weshipit/pages/index.tsx
- package.json
- yarn.lock
> feat: 🎸 add disclosure for faq

- apps/weshipit/pages/api/links.ts
- apps/weshipit/pages/coding-retreat.tsx
> feat: 🎸 implement coding-retreat page

- apps/weshipit/pages/audit/index.tsx
- apps/weshipit/pages/index.tsx
- libs/ui/src/index.ts
- libs/ui/src/lib/button/button.stories.tsx
- libs/ui/src/lib/clients-list/clients-list-audit.tsx
- libs/ui/src/lib/section/section.spec.tsx
- libs/ui/src/lib/section/section.tsx
> feat: 🎸 add section component

- apps/weshipit/next-env.d.ts
- apps/weshipit/pages/index.tsx
- libs/ui/src/lib/card/workflow-card.tsx
> fix: 🐛 workflow steps design

- apps/weshipit/pages/audit/index.tsx
> fix: 🐛 remove section count

- apps/weshipit/pages/index.tsx
> fix: 🐛 define what make a great app

- libs/ui/src/lib/react-native-tools/type-filter/type-filter.tsx
> fix: 🐛 update filter buttons

- apps/weshipit/pages/french-react-native-apps.tsx
- apps/weshipit/pages/index.tsx
- apps/weshipit/tailwind.config.js
- libs/ui/src/index.ts
- libs/ui/src/lib/button/button.tsx
- libs/ui/src/lib/footer/footer.tsx
- libs/ui/src/lib/hero/hero-banner.tsx
- libs/ui/src/lib/hero/hero.stories.tsx
- libs/ui/src/lib/hero/phone-animation.tsx
- libs/ui/src/lib/text/text.tsx
- package.json
- yarn.lock
> feat: 🎸 add blueprint on homepage

- apps/weshipit/components/trusted-consultants-section.tsx
- apps/weshipit/pages/home.tsx
- apps/weshipit/pages/index.tsx
- libs/ui/src/lib/avatar/avatar.tsx
- libs/ui/src/lib/bento/bento.tsx
- libs/ui/src/lib/button/link-button.tsx
- libs/ui/src/lib/card/card.tsx
- libs/ui/src/lib/hero/hero.stories.tsx
- libs/ui/src/lib/hero/phone-animation.tsx
- nx.json
- package.json
- yarn.lock
> refactor: 💡 trusted consultants section

- apps/weshipit/pages/api/feedback.ts
- apps/weshipit/pages/react-native-migration/index.tsx
- libs/ui/src/lib/footer/footer.tsx
> feat: 🎸 add migration-page

- apps/weshipit/pages/french-react-native-apps.tsx
> fix: 🐛 add filter for french apps

- .github/PULL_REQUEST_TEMPLATE.md
- apps/weshipit/pages/api/og.tsx
- apps/weshipit/public/robots.txt
- package.json
- yarn.lock
> feat: 🎸 og is back
